apiVersion: batch/v1
kind: CronJob
metadata:
  name: clear-sessions
  namespace: edu-happy-goldberg
spec:
  schedule: "16 7 * * *"
  startingDeadlineSeconds: 150
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10
      template:
        spec:
          containers:
          - name: clear-sessions
            image: djeedo/django-app:38b367a
            imagePullPolicy: Never
            command:
              - python
              - manage.py
              - clearsessions
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: url
              - name: SECRET_KEY
                valueFrom:
                  configMapKeyRef:
                    name: django-cm
                    key: secret-key
              - name: DEBUG
                valueFrom:
                  configMapKeyRef:
                    name: django-cm
                    key: debug
              - name: ALLOWED_HOSTS
                valueFrom:
                  configMapKeyRef:
                    name: django-cm
                    key: allowed-hosts
          restartPolicy: OnFailure