apiVersion: v1
kind: Service
metadata:
  name: django-deploy
  namespace: edu-happy-goldberg
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30231
    protocol: TCP