apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: edu-happy-goldberg
  labels:
    app: nginx-a
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80