apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: edu-happy-goldberg
spec:
  type: NodePort
  selector:
    app: nginx-a
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30231
    protocol: TCP