apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deploy
  labels:
    app: django-deploy
spec:
  selector:
    matchLabels:
      app: django-deploy
  template:
    metadata:
      labels:
        app: django-deploy
    spec:
      containers:
        - name: django-app
          image: django_app:latest
          ports:
          - containerPort: 80
          imagePullPolicy: Never
          envFrom:
          - configMapRef:
              name: django-cm